FORMAT: 1A
HOST: http://www.google.com

# Owlery
Owlery provides a web API for an [OWL API](http://owlapi.sourceforge.net)-based reasoner containing a configurable set of ontologies (a "knowledgebase").

## Knowledgebase [/kbs/{kb}]
### Display Knowledgebase information and status [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
+ Response 200 (text/plain)

        Knowledgebase phenoscape is consistent
+ Response 404

        No such knowledgebase: phenoscape
        
## Subclasses [/kbs/{kb}/subclasses{?object,prefixes,direct}]
### Get subclasses of a named class or expression [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... URI for a named class in the KB
    + prefixes (optional, string)
    + direct = `true` (optional, boolean)
+ Response 200 (text/plain)

## Superclasses [/kbs/{kb}/superclasses{?object,prefixes,direct}]
### Get superclasses of a named class or expression [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... URI for a named class in the KB
    + prefixes (optional, string)
    + direct = `true` (optional, boolean)
+ Response 200 (text/plain)

## Equivalent classes [/kbs/{kb}/equivalent{?object,prefixes}]
### Get equivalent classes of a named class or expression [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... URI for a named class in the KB
    + prefixes (optional, string)
+ Response 200 (text/plain)

## Satisfiability [/kbs/{kb}/satisfiable{?object,prefixes}]
### Returns whether the given named class or expression is satisfiable [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... URI for a named class in the KB
    + prefixes (optional, string)
+ Response 200 (text/plain)

        true
        
## Individuals [/kbs/{kb}/individuals{?object,prefixes,direct}]
### Get individuals of a named class or expression [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... URI for a named class in the KB
    + prefixes (optional, string)
    + direct = `true` (optional, boolean)
+ Response 200 (text/plain)

## Types [/kbs/{kb}/types{?object,prefixes,direct}]
### Get types of a named individual [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + object (required, string, `http://example.org/person/1234`) ... URI for a named individual in the KB
    + prefixes (optional, string)
    + direct = `true` (optional, boolean)
+ Response 200 (text/plain)

## SPARQL endpoint [/kbs/{kb}/sparql{?query}]
Perform SPARQL query using Owlet-style embedded class expressions
### Perform SPARQL query encoded in URL parameter [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + query (required, string) ... SPARQL query
+ Response 200 (application/sparql-results+xml)

### Perform SPARQL query contained in request body [POST]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + query (optional, string) ... Include `query` parameter in request body if using `application/x-www-form-urlencoded` format. It is not used with `application/sparql-query` request body.
+ Request (application/sparql-query)
+ Request (application/x-www-form-urlencoded)
+ Response 200 (application/sparql-results+xml)

## SPARQL query expander [/kbs/{kb}/expand{?query}]
Expand a SPARQL query, transforming Owlet-style embedded class expressions into `FILTER`s
### Expand SPARQL query encoded in URL parameter [GET]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
    + query (required, string) ... SPARQL query
+ Response 200 (application/sparql-query)

### Expand SPARQL query contained in request body [POST]

+ Parameters
    + kb (string, `phenoscape`) ... label for a knowledgebase loaded into Owlery
+ Response 200 (application/sparql-query)
