name: Docker Image CI

on:
  push:
    #branches: '**'
    #tags: 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: cd Docker; docker build --tag owlery:${GITHUB_REF#refs/heads/} .
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: phenoscape/owlery
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
