# Adapted from this posting:
# https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote


    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: src/main/resources/docs/swagger.yaml
